# Generated by Django 4.0.3 on 2022-03-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_bill_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalbill',
            name='bill_number',
            field=models.CharField(max_length=200),
        ),
    ]
